TW/eUseControl/eUseControl.Web/Models/UDbTable.cs
namespace eUseControl.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class UDbTable
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(30)]
        public string username { get; set; }

        [Key]
        [Column(Order = 2)]
        [StringLength(50)]
        public string password { get; set; }

        [Key]
        [Column(Order = 3)]
        [StringLength(30)]
        public string email { get; set; }

        [Key]
        [Column(Order = 4)]
        public DateTime LastLogin { get; set; }

        [Key]
        [Column(Order = 5)]
        [StringLength(30)]
        public string LasIp { get; set; }

        [Key]
        [Column(Order = 6)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Level { get; set; }
    }
}

TW/eUseControl/eUseControl.Web/Models/UserData.cs
using eUseControl.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eUseControl.Web.Models
{
    public class UserData
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public URole Level { get; set; }
        //public List<string> Products { get; set; }
    }
}

TW/eUseControl/eUseControl.Web/Models/UserLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eUseControl.Web.Models
{
    public class UserLogin
    {
        public string Credential { get; set; }
        public string Password { get; set; }
        public string LoginIp { get; set; }
        public DateTime LoginDateTime { get; set; }
    }
}

TW/eUseControl/eUseControl.Web/Models/UserRegister.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eUseControl.Web.Models
{
    public class UserRegister
    {
        [Required]
        [Display(Name = "Nume utilizator")]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Parola")]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

TW/eUseControl/eUseControl.Web/Controllers/AdminController.cs
using eUseControl.Web.Extension;
using System.Web.Mvc;
using static eUseControl.Web.Controllers.AdminModAtribute;

namespace eUseControl.Web.Controllers
{
    public class AdminController : Controller
    {
        [AdminMod]
        public ActionResult Index()
        {
           // SessionStatus();
           // if((string)System.Web.HttpContext.CurrentSession["LoginStatus"]=="login")
            //{
              //  var user = System.Web.HttpContext.Current.GetMySessionObject();
                //return View(user);
            //}
                
                return View();
        }
    }
}

TW/eUseControl/eUseControl.Web/Controllers/AuthentificationController.cs
using eUseControl.BusinessLogic;
using eUseControl.BusinessLogic.Interfaces;
using eUseControl.Domain.Entities.User;
using eUseControl.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eUseControl.Web.Controllers
{
    public class AuthentificationController : Controller
    {
        // GET: Login
        private readonly ISession _session;

        public AuthentificationController()
        {
            var bl = new BussinesLogic();
            _session = bl.GetSessionBl();
        }

        //Get: Login
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost] //transmiterea datelor client sau a formularului catre server
        [ValidateAntiForgeryToken]//pentru a preveni falsificarea cererilor între site-uri
        public ActionResult Index(UserLogin login)
        {
            if (ModelState.IsValid)
            {
                ULoginData data = new ULoginData
                {
                    Credential = login.Credential,
                    Password = login.Password,
                    LoginIp = Request.UserHostAddress,
                    LoginDateTime = DateTime.Now
                };

                var userLogin = _session.UserLogin(data);
                if (userLogin.Status)
                {
                    //add cookie
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", userLogin.StatusMsg);
                    return View();
                }
            }

            return View();
        }
    }
}

TW/eUseControl/eUseControl.Web/Controllers/BaseController.cs
using eUseControl.BusinessLogic.Interfaces;
using System;
using System.Linq;
using System.Web.Mvc;
using eUseControl.Web.Extension;

namespace eUseControl.Web.Controllers
{
    public class BaseController : Controller
    {
        private readonly ISession _session;

        public BaseController()
        {
            var bl = new BusinessLogic.BussinesLogic();
            _session = bl.GetSessionBl();
        }

        

    }
}

TW/eUseControl/eUseControl.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eUseControl.Web.Models;

namespace eUseControl.Web.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            UserData u = new UserData();
            u.Username = "Customer";
            //u.Products = new List<string> { "Product #1", "Product #2" };
            return View(u);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TW/eUseControl/eUseControl.Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eUseControl.Web.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }
    }
}

TW/eUseControl/eUseControl.Web/Controllers/RegisterController.cs
using System.Web.Mvc;
using eUseControl.Web.Models;
using eUseControl.BusinessLogic.Interfaces;
using System.Web;
using eUseControl.Domain.Entities.User;

namespace eUseControl.Web.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IRegister _register;
        private readonly ISession _session;
        // GET: Login
        public RegisterController()
        {
            var bl = new BusinessLogic.BussinesLogic();
            _register = bl.GetRegisterBL();
            var ss = new BusinessLogic.BussinesLogic();
            _session = ss.GetSessionBl();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserRegister user)
        {
            URegisterData data = new URegisterData
            {
                Username = user.Username,
                Password = user.Password,
                Email = user.Email
            };

            _register.UserRegister(data);

            ULoginData u = new ULoginData
            {
                Credential = user.Username,
                Password = user.Password
            };

            _session.UserLogin(u);

            //HttpCookie cookie = _session.GenCookie(u.Credential);
            //ControllerContext.HttpContext.Response.Cookies.Add(cookie);

            return RedirectToAction("Index", "Home");
        }
    }
}

TW/eUseControl/eUseControl.Web/Views/Admin/Index.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Adm.cshtml";
}
<body class="blank">
    <div class="color-line"></div>
    <div class="container">
        <div class="row">
            <br><br><br><br><br><br>
            <div class="col-md-4" style="color: transparent;"></div>
            <div class="col-md-4">
                <div class="text-center m-b-lg">
                    <h3>Administrator Postări</h3>
                </div>
                <div class="hpanel" >
                    <div class="panel-body">
                        <form action="#" id="">
                            <div class="row">
                                <div class="form-group col-lg-12">
                                    <label>Introduce denumire</label>
                                    <input type="" value="" id="" class="form-control" name="">
                                </div>
                                <div class=" col-lg-12">
                                    <label>Introduce text</label>
                                    <input type="password" value="" id="" class="form-control" name="">
                                </div>
                                <div class="form-group col-lg-12">
                                    <label>Introduce autor</label>
                                    <input type="" value="" id="" class="form-control" name="">
                                </div>
                                <div class="text-center">
                                    <button class="btn btn-success">Add</button>
                                    <button class="btn btn-default">Cancel</button>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
</body>

TW/eUseControl/eUseControl.Web/Views/Authentification/Index.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutB.cshtml";
}

TW/eUseControl/eUseControl.Web/Views/Authentification/Login.cshtml
@model eUseControl.Web.Models.UserLogin
@using System.Web.Optimization
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutBlank.cshtml";
}
<!DOCTYPE html>
<html>
<head>
</head>
<body class="blank">
    <div class="login-container">
        <div class="row">
            <div class="col-md-10">
                <div class="text-center m-b-md">
                    <h3> LOGIN</h3>
                </div>
                <div class="hpanel">
                    <div class="panel-body">
                        @Html.ValidationSummary(true)
                        @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @id = "LoginForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <form  id="loginForm" novalidate>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Credential, new { @class = "control-label" })
                                    @Html.TextBoxFor(m => m.Credential, new
                               {
                                   type = "Username",
                                   name = "Username",
                                   placeholder = "example@gmail.com",
                                   title = "Please enter you username",
                                   value = "",
                                   id = "username",
                                   @class = "form-control"
                               })
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                                    @Html.TextBoxFor(m => m.Password, new 
                                {
                                @class="form-control",
                                type="password",
                                title="Please enter your password" ,
                                placeholder="******" ,
                                value="",
                                name="password",
                                id="password"
                                })
                                </div>
                                <button class="btn btn-success btn-block" type="submit"><a href="@Url.Action("Index","Authentification")">Login</a></button>
                                <a class="btn btn-default btn-block" href="@Url.Action("Register", "Authentification")">Register</a>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    @section Scripts{
        @Scripts.Render("~/bundles/validation/js")
        
        <script type="text/javascript">
            $(function () {
                $("#LoginForm").validate({
                    rules: {
                        Username: {
                            required: true
                        },
                        Password: {
                            required: true
                        }
                    },
                    submitHandler: function (form) {
                        form.submit();
                    },
                    errorPlacement: function (error, element) {
                        $(element)
                            .closeset("form")
                            .find("label[for='" + element.attr("id") + "']")
                            .append(error);
                    },
                    errorElement: "span"
                });
            });
        </script>
        }
</body>
</html>

TW/eUseControl/eUseControl.Web/Views/Authentification/Register.cshtml
@using System.Web.Optimization
@model eUseControl.Web.Models.UserRegister
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_LayoutBlank.cshtml";
}

<!DOCTYPE html>
<html>
<head>
</head>
<body class="blank">
    <div class="register-container">
        <div class="row">
            <div class="col-md-3" style="color: transparent;"></div>
                <div class="col-md-6">
                    <div class="text-center m-b-md">
                        <h3>Registration</h3>
                    </div>
                    <div class="hpanel">
                        <div class="panel-body">


                            @using (Html.BeginForm("Index", "Register", FormMethod.Post, new { @id = "RegisterForm" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Username, new { @class = "control-label" })
                                    @Html.TextBoxFor(m => m.Username, new
                                    {
                                        placeholder = "...",
                                        title = "Enter the username",
                                        value = "",
                                        name = "name",
                                        id = "name",
                                        @class = "form-control",
                                        type = "username"
                                    })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                                    @Html.TextBoxFor(m => m.Password, new
                                    {
                                        placeholder = "...",
                                        title = "Introduceti parola",
                                        value = "*",
                                        name = "parola",
                                        id = "parola",
                                        @class = "form-control",
                                        type = "password"
                                    })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                                    @Html.TextBoxFor(m => m.Email, new
                                    {
                                        placeholder = "...",
                                        title = "Introduceti email-ul",
                                        value = "",
                                        name = "email",
                                        id = "email",
                                        type = "email",
                                        @class = "form-control"
                                    })
                                </div>
                            }

                            <div class="text-center">
                                <button class="btn btn-success">
                                <a href="@Url.Action("Index","Authentification")">Register</a></button>
                                
                            </div>

                        </div>
                    </div>
                </div>
            </div>
    </div>
</body>
</html>

TW/eUseControl/eUseControl.Web/Views/Authentification/SignUp.cshtml
@{
    ViewBag.Title = "SignUp";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laborator TW</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<style>
    body {
        background-color: #e9f79dd8;
        background-repeat: no-repeat;
        background-attachment: top;
        background-size: 100%;
    }
</style>
<body>

    <br><br><br><br><br><br><br><br><br><br>

    <div class="container-fluid">
        <div class="col-lg-3" style="color: transparent;"></div>
        <div class="col-lg-6" style="background-color:  rgb(223, 208, 205);">
            <h6 style="font-size:24px">    Sign Up</h6>
        </div>
    </div>
    <div class="container-fluid">
        <div class="col-lg-3" style="color: transparent;"></div>
        <div class="col-lg-6" style="background-color: rgb(230, 202, 197);">
            <br>
            <div class="col-lg-1" style="color: transparent;"></div>
            <div class="container-fluid">
                <div class="col-lg-5">
                    <div class="input-group margin-bottom-sm">
                        <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                        <input class="form-control" type="text" placeholder="Nume">
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                        <input class="form-control" type="text" placeholder="Prenume">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="col-lg-3" style="color: transparent;"></div>
        <div class="col-lg-6" style="background-color: rgb(221, 185, 179);">
            <br>
            <div class="col-lg-1" style="color: transparent;"></div>
            <div class="container-fluid">
                <div class="col-lg-5">
                    <div class="input-group margin-bottom-sm">
                        <span class="input-group-addon"><i class="fa fa-mobile fa-fw"></i></span>
                        <input class="form-control" type="text" placeholder="Nr de telefon">
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-map-marker fa-fw"></i></span>
                        <input class="form-control" type="text" placeholder="Domiciliu">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="col-lg-3" style="color: transparent;"></div>
        <div class="col-lg-6" style="background-color: rgb(221, 185, 179);">
            <br>
            <div class="col-lg-1" style="color: transparent;"></div>
            <div class="container-fluid">
                <div class="col-lg-5">
                    <div class="input-group margin-bottom-sm">
                        <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
                        <input class="form-control" type="text" placeholder="Email">
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span>
                        <input class="form-control" type="text" placeholder="Data nașterii">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="col-lg-3" style="color: transparent;"></div>
        <div class="col-lg-6" style="background-color: rgb(221, 185, 179);">
            <br>
            <div class="col-lg-1" style="color: transparent;"></div>
            <div class="container-fluid">
                <div class="col-lg-5">
                    <div class="input-group margin-bottom-sm">
                        <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                        <input class="form-control" type="password" placeholder="Password">
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-check fa-fw"></i></span>
                        <input class="form-control" type="password" placeholder="Confirmă parola">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="col-lg-3" style="color: transparent;"></div>
        <div class="col-lg-6" style="background-color: rgb(221, 185, 179);">
            <br>
            <div class="col-lg-8" style="color: transparent;"></div>
            <div class="col-lg-1">
                <button class="btn btn-success"> Sign Up <i class="fa fa-flash fa-fw"></i></span></button>
            </div>
            <br><br><br>
        </div>
    </div>


    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

TW/eUseControl/eUseControl.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TW/eUseControl/eUseControl.Web/Views/Home/Index.cshtml
@using System.Web.Optimization
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}

TW/eUseControl/eUseControl.Web/Views/Shared/_Carousel.cshtml
@{
    ViewBag.Title = "Carousel";
}
<ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
</ol>

<!-- Wrapper for slides -->
<div class="carousel-inner" style="height: 550px;">
    <div class="item active">
        <img src="@Url.Content("~/Content/img/2.jpg")" style="width:100%;">
    </div>

    <div class="item">
        <img src="@Url.Content("~/Content/img/1.jpg")" style="width:100%;">
    </div>

    <div class="item">
        <img src="@Url.Content("~/Content/img/book-glasses1.jpg")" style="width:100%;">
    </div>
</div>

<!-- Left and right controls -->
<a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
</a>

TW/eUseControl/eUseControl.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bib</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        @{ Html.RenderPartial("_Navbar");}
    </nav>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        @{ Html.RenderPartial("_Carousel");}
    </div>

    <div>
        @{ Html.RenderPartial("_Body");}
    </div>
        @RenderBody()

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

</body>
</html>

TW/eUseControl/eUseControl.Web/Views/Shared/_Nav.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Nav";
}
<div class="container-fluid">
    <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="@Url.Action("Index","Home")" class="navbar-brand">Librio</a>
    </div>
    <div class="collapse navbar-collapse">
        <div style="float:right;">
            <form role="form" class="navbar-form form-inline">
                <button type="button" class="btn btn-md" style="background-color:#ffffff">
                    <span class="glyphicon glyphicon-glyphicon glyphicon-log-in" aria-hidden="true"
                          style="color:#0f0d0d"></span><a href="@Url.Action("Login","Authentification")">  Login</a>
                </button>
                <button type="button" class="btn btn-md" style="background-color: #ffffff">
                    <span class="glyphicon glyphicon-glyphicon glyphicon-user" aria-hidden="true"
                          style="color: #0f0d0d"></span><a href="@Url.Action("Register","Authentification")"> Register</a>
                </button>
            </form>
        </div>
    </div>
</div>

TW/eUseControl/eUseControl.Web/Views/Shared/_Nav_Adm.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Navbar";
}
<div class="container-fluid">
    <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="@Url.Action("Index","Home")" class="navbar-brand">Librio</a>
    </div>
    <div class="collapse navbar-collapse">
        <div>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="@Url.Action("Index","Home")">Despre noi</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="https://www.librarius.md/">Carti</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="https://www.elefant.md/hp-carte">Oferte</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="@Url.Action("Index","Admin")"> Admin</a></li>
            </ul>
        </div>
        <div style="float:right;">
            <form role="form" class="navbar-form form-inline">
                <button type="button" class="btn btn-md" style="background-color:#ffffff">
                    <span  aria-hidden="true"
                          style="color:#0f0d0d"></span><a href="@Url.Action("Index","Home")">  LogOut</a>
                </button>
                
            </form>
        </div>
    </div>
</div>

TW/eUseControl/eUseControl.Web/Views/Shared/_Navbar.cshtml
@using System.Web.Optimization
@{
    ViewBag.Title = "Navbar";
}
<div class="container-fluid">
    <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="@Url.Action("Index","Home")" class="navbar-brand">Librio</a>
    </div>
    <div class="collapse navbar-collapse">
        <div>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="@Url.Action("Index","Home")">Despre noi</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="https://www.librarius.md/">Carti</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li><a href="https://www.elefant.md/hp-carte">Oferte</a></li>
            </ul>
        </div>
        <div style="float:right;">
            <form role="form" class="navbar-form form-inline">
                <button type="button" class="btn btn-md" style="background-color:#ffffff">
                    <span class="glyphicon glyphicon-glyphicon glyphicon-log-in" aria-hidden="true"
                          style="color:#0f0d0d"></span><a href="@Url.Action("Login","Authentification")">  Login</a> 
                </button>
                <button type="button" class="btn btn-md" style="background-color: #ffffff">
                    <span class="glyphicon glyphicon-glyphicon glyphicon-user" aria-hidden="true"
                          style="color: #0f0d0d"></span><a  href="@Url.Action("Register","Authentification")"> Register</a>
                </button>
            </form>
        </div>
    </div>
</div>